# fly.toml app configuration file generated for citymart-bot on 2025-07-27T23:59:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "citymart-services"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  memory     = "256mb"
  cpu_kind   = "shared"
  cpus       = 1
  memory_mb  = 256
